### ISSUE TITLE
Questions about training Multi-view Diffusion Models

### ISSUE THREAD

**Issue by snowflakewang** [AiuniAI/Unique3D#12]
Hello, thank you for your great work in highly detailed Image-to-3D generation!
I am inquisitive about training a multi-view diffusion model since it is an efficient technique in the Image-to-3D field. If I want to write a training script by myself, are there any existing scripts I can refer to? Or how soon will you release your MVDiffusion training code?

Thanks a lot!!! :)

**Comment by wukailu** [comment]
We plan to release the training code and corresponding dataset in July.

**Comment by Aiunii** [comment]
Hey! 
Welcome to 4D digital art creation universe—— Aiuni.

🤖First, join our community by:
 https://discord.gg/aiuni

🦄️Then you will get the invitation code at “getting-started” channel.

Start your creative journey and have fun!🌟
> From: ***@***.***>
> Date:  Thu, Jun 6, 2024, 5:40 PM
> Subject:  [AiuniAI/Unique3D] Questions about training Multi-view Diffusion Models (Issue #12)
> To: ***@***.***>
> Cc: ***@***.***>
> Hello, thank you for your great work in highly detailed Image-to-3D generation!
> 
I am inquisitive about training a multi-view diffusion model since it is an efficient technique in the Image-to-3D field. If I want to write a training script by myself, are there any existing scripts I can refer to? Or how soon will you release your MVDiffusion training code?
