### ISSUE TITLE
For Windows users

### ISSUE THREAD

**Issue by jtydhr88** [AiuniAI/Unique3D#15]
I got it working on my Windows.
It might require Visual Studio Build Tools. However, I am not sure because my local already installed previously. If it needs, you can find from [Visual Studio Build Tools](https://visualstudio.microsoft.com/downloads/?q=build+tools).

**Env**
1. WIndows 10
2. Conda - Python 3.11
3. 3090
4. Cuda 12.1

**Setup Steps**
1. conda create -n unique3d-py311 python=3.11
2. conda activate unique3d-py311
3. pip install torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu121
4. (Download the trition whl from https://huggingface.co/madbuda/triton-windows-builds, because I use python 311, so download whl build for py311 and install manually) pip install triton-2.1.0-cp311-cp311-win_amd64.whl
5. pip install Ninja
6. (Due the latest diffusers is not compatible to the code of repo, we MUST install this for diffusers manually) pip install diffusers==0.27.2
7. pip install grpcio werkzeug tensorboard-data-server
8. remove **torch>=2.0.1, diffusers>=0.26.3, xformers, onnxruntime_gpu** from requirement.txt
![image](https://github.com/AiuniAI/Unique3D/assets/860985/9750016c-5594-4d0a-b819-09e206ae34b8)
9. pip install -r requirements.txt
10. pip uninstall onnxruntime
11. pip uninstall onnxruntime-gpu
12. (We MUST uninstall onnxruntime and onnxruntime-gpu first, then install this given version manually) pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/

**Runtime**
1. you need to create the output folder **tmp\gradio** under the running driver by yourself, for me, it is F:\tmp\gradio
2. You will see the error of onnxruntime 
![image](https://github.com/AiuniAI/Unique3D/assets/860985/db4b1b52-6c55-463b-860f-ef32849f9fc6)
but it would not effect the generation of the mesh (maybe?)

**Quick test**
![image](https://github.com/AiuniAI/Unique3D/assets/860985/6c059c95-2c99-48d7-8aa3-64830f6a3be6)
![image](https://github.com/AiuniAI/Unique3D/assets/860985/fa34f3a1-37af-488f-8b2f-1c0fe2329256)

Good luck~

**Comment by maybeaduck** [comment]
I have problems with Microsoft Visual C++ installation. Build tools is installed and I installed Visual C++ Redistributable. But this error is still showing. Can you suggest what can be done?

PS E:\Unity\Unique3D> python app/gradio_local.py --port 7860
Warning! extra parameter in cli is not verified, may cause erros.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00, 13.70it/s]
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2mvimg.StableDiffusionImage2MVCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Warning! extra parameter in cli is not verified, may cause erros.
C:\Users\maybe\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading pipeline components...: 100%|██████████████████████████████████████████████████| 5/5 [00:00<00:00, 2498.99it/s]
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2img.StableDiffusionImageCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Traceback (most recent call last):
  File "E:\Unity\Unique3D\app\gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "E:\Unity\Unique3D\app\gradio_3dgen.py", line 10, in <module>
    from scripts.multiview_inference import geo_reconstruct
  File "E:\Unity\Unique3D\scripts\multiview_inference.py", line 4, in <module>
    from scripts.project_mesh import multiview_color_projection
  File "E:\Unity\Unique3D\scripts\project_mesh.py", line 98, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
                         ^^^^^^^^^^^^^^^^^^^
  File "E:\Unity\Unique3D\scripts\project_mesh.py", line 70, in __init__
    self._glctx = dr.RasterizeGLContext(output_db=False, device=device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maybe\AppData\Local\Programs\Python\Python311\Lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maybe\AppData\Local\Programs\Python\Python311\Lib\site-packages\nvdiffrast\torch\ops.py", line 43, in _get_plugin
    raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
RuntimeError: Could not locate a supported Microsoft Visual C++ installation

**Comment by Gitterman69** [comment]
bump

**Comment by Aiunii** [comment]
Hey! 
Welcome to 4D digital art creation universe—— Aiuni.

🤖First, join our community by:
 https://discord.gg/aiuni

🦄️Then you will get the invitation code at “getting-started” channel.

Start your creative journey and have fun!🌟

**Comment by DamienCz** [comment]
for autodownload 
(unique3d-py311) E:\Unique3D>pip show torch
Name: torch
Version: 2.3.0+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: C:\Users\WS01\anaconda3\envs\unique3d-py311\Lib\site-packages
Requires: filelock, fsspec, jinja2, mkl, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision, xformers

(unique3d-py311) E:\Unique3D>
then ....
Failed to build pytorch3d
ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects

how to deal with this problem...

**Comment by jtydhr88** [comment]
See https://github.com/AiuniAI/Unique3D/issues/29

**Comment by jayc0207** [comment]
python app\gradio_local.py --port 7860
-------------------------------------------------------------------------
Warning! extra parameter in cli is not verified, may cause erros.
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 416.27it/s]
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2mvimg.StableDiffusionImage2MVCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Warning! extra parameter in cli is not verified, may cause erros.
C:\Users\jayis\anaconda3\envs\unique3d-py311\Lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "D:\Unique3D\Unique3D\app\gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "D:\Unique3D\Unique3D\app\gradio_3dgen.py", line 7, in <module>
    from app.custom_models.normal_prediction import predict_normals
  File "D:\Unique3D\Unique3D\app\custom_models\normal_prediction.py", line 10, in <module>
    trainer, pipeline = load_pipeline(training_config, checkpoint_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Unique3D\Unique3D\app\custom_models\utils.py", line 65, in load_pipeline
    configurable_unet.unet.to(device, dtype=weight_dtype)
  File "C:\Users\jayis\anaconda3\envs\unique3d-py311\Lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayis\anaconda3\envs\unique3d-py311\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\jayis\anaconda3\envs\unique3d-py311\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\jayis\anaconda3\envs\unique3d-py311\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 7 more times]
  File "C:\Users\jayis\anaconda3\envs\unique3d-py311\Lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\jayis\anaconda3\envs\unique3d-py311\Lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
           ^^^^^
**torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU**
-----------------------------------------------------------------------------------------------------------
How to solve this problem ?

**Comment by turugi-ni** [comment]
> I had a go getting this working under Windows too. For my setup I am supporting CUDA 11.8 and Python 3.10.x because that is what I use for all the AI/ML scripts in Visions of Chaos.
> 
> This is my install.bat file. Save to an empty directory (in my case D:\Tests\Unique3D) and run it command line to install Unique3D automatically.
> 
> ```
> @echo off
> 
> echo *** Deleting Unique3D directory if it exists
> if exist Unique3D\. rd /S /Q Unique3D
> 
> echo *** Cloning Unique3D repository
> git clone https://huggingface.co/spaces/Wuvin/Unique3D
> cd Unique3D
> 
> echo *** Creating venv
> python -m venv venv
> call venv\scripts\activate.bat
> 
> python -m pip install --upgrade pip
> pip install torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu118
> pip install https://softology.pro/wheels/triton-2.1.0-cp310-cp310-win_amd64.whl
> pip install ninja
> pip install diffusers==0.27.2
> pip install grpcio werkzeug tensorboard-data-server
> 
> echo *** Removing linux specific packages from requirements.txt
> type requirements.txt | findstr /v pytorch3d > stripped.txt
> del requirements.txt
> ren stripped.txt requirements.txt
> type requirements.txt | findstr /v ort-nightly > stripped.txt
> del requirements.txt
> ren stripped.txt requirements.txt
> type requirements.txt | findstr /v onnxruntime > stripped.txt
> del requirements.txt
> ren stripped.txt requirements.txt
> type requirements.txt | findstr /v torch-scatter > stripped.txt
> del requirements.txt
> ren stripped.txt requirements.txt
> type requirements.txt | findstr /v diffusers > stripped.txt
> del requirements.txt
> ren stripped.txt requirements.txt
> type requirements.txt | findstr /v xformers > stripped.txt
> del requirements.txt
> ren stripped.txt requirements.txt
> type requirements.txt | findstr /v torch > stripped.txt
> del requirements.txt
> ren stripped.txt requirements.txt
> 
> echo *** Installing requirments.txt
> pip install -r requirements.txt
> 
> echo *** Installing other required packages
> pip uninstall -y xformers
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts xformers==0.0.25 --index-url https://download.pytorch.org/whl/cu118
> pip uninstall -y torch
> pip uninstall -y torch
> pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch==2.2.1+cu118 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> 
> pip uninstall onnxruntime
> pip uninstall onnxruntime-gpu
> pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
> pip install ort-nightly-gpu
> 
> pip install https://files.pythonhosted.org/packages/b2/3c/6205090507ea96e6e56d0deda8d0fc4c507026ef3772e55b637a5d0b7c61/spaces-0.28.3-py3-none-any.whl
> 
> call venv\scripts\deactivate.bat
> cd ..
> 
> echo *** Finished Unique3D install
> echo.
> ```
> 
> Once the install finishes I try running `python gradio_app\gradio_local.py --port 7860` which gives this error
> 
> ```
> Traceback (most recent call last):
>   File "D:\Tests\Unique3D\Unique3D\gradio_app\gradio_local.py", line 20, in <module>
>     from gradio_app.gradio_3dgen import create_ui as create_3d_ui
>   File "D:\Tests\Unique3D\Unique3D\.\gradio_app\gradio_3dgen.py", line 1, in <module>
>     import spaces
> ModuleNotFoundError: No module named 'spaces'
> ```
> 
> After `pip install spaces` and rerunning it I get
> 
> ```
> python gradio_app\gradio_local.py --port 7860
> Traceback (most recent call last):
>   File "D:\Tests\Unique3D\Unique3D\gradio_app\gradio_local.py", line 20, in <module>
>     from gradio_app.gradio_3dgen import create_ui as create_3d_ui
>   File "D:\Tests\Unique3D\Unique3D\.\gradio_app\gradio_3dgen.py", line 1, in <module>
>     import spaces
>   File "D:\Tests\Unique3D\Unique3D\venv\lib\site-packages\spaces\__init__.py", line 10, in <module>
>     from .zero.decorator import GPU
>   File "D:\Tests\Unique3D\Unique3D\venv\lib\site-packages\spaces\zero\decorator.py", line 21, in <module>
>     from .wrappers import regular_function_wrapper
>   File "D:\Tests\Unique3D\Unique3D\venv\lib\site-packages\spaces\zero\wrappers.py", line 15, in <module>
>     from multiprocessing.context import ForkProcess
> ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (D:\Python\lib\multiprocessing\context.py)
> ```
> 
> ForkProcess seems to be Linux only so no go for me. If we can get a single click install.bat working that would really help Windows users (and me so I can add support for Unique3D into Visions of Chaos).

Windows does not support ForkProcess, open venv\lib\site-packages\spaces\zero\wrappers.py in a text editor tool, Change from multiprocessing.context import ForkProcess to from multiprocessing.context import SpawnProcess in line 15 and Try changing line 50 Process = from multiprocessing.get_context('fork').Process to Process = from multiprocessing.get_context('spawn').Process, Still, we encounter new errors. Unique3D has too many dependencies of dependencies and more dependencies of dependencies I gave up installing on Windows.

**Comment by Cicoa123** [comment]
Traceback (most recent call last):
  File "C:\Users\zzr\Unique3D\app\gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "C:\Users\zzr\Unique3D\app\gradio_3dgen.py", line 6, in <module>
    from app.custom_models.mvimg_prediction import run_mvprediction
  File "C:\Users\zzr\Unique3D\app\custom_models\mvimg_prediction.py", line 8, in <module>
    from app.custom_models.utils import load_pipeline
  File "C:\Users\zzr\Unique3D\app\custom_models\utils.py", line 6, in <module>
    from custum_3d_diffusion import modules
  File "C:\Users\zzr\Unique3D\custum_3d_diffusion\modules.py", line 14, in <module>
    from custum_3d_diffusion.trainings import base, image2mvimage_trainer, image2image_trainer
  File "C:\Users\zzr\Unique3D\custum_3d_diffusion\trainings\base.py", line 14, in <module>
    from custum_3d_diffusion.custum_modules.unifield_processor import ConfigurableUNet2DConditionModel, AttnConfig
  File "C:\Users\zzr\Unique3D\custum_3d_diffusion\custum_modules\unifield_processor.py", line 3, in <module>
    from diffusers import UNet2DConditionModel
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "C:\Users\zzr\anaconda3\envs\unique3dpy311\Lib\site-packages\diffusers\utils\import_utils.py", line 709, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zzr\anaconda3\envs\unique3dpy311\Lib\site-packages\diffusers\utils\import_utils.py", line 708, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zzr\anaconda3\envs\unique3dpy311\Lib\site-packages\diffusers\utils\import_utils.py", line 720, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.unets.unet_2d_condition because of the following error (look up to see its traceback):
expected str, bytes or os.PathLike object, not NoneType
####################
is this place due to  the windows11?Who can tell me some method,plese.I dn reinstall another system.

**Comment by mmestiri** [comment]
i have this error : python app/gradio_local.py --port 7860
Traceback (most recent call last):
  File "C:\Users\mmest\OneDrive\Desktop\generative AI\Unique3D-main\Unique3D-main\app\gradio_local.py", line 20, in <module>
    from app.gradio_3dgen import create_ui as create_3d_ui
  File "C:\Users\mmest\OneDrive\Desktop\generative AI\Unique3D-main\Unique3D-main\app\gradio_3dgen.py", line 6, in <module>
    from app.custom_models.mvimg_prediction import run_mvprediction
  File "C:\Users\mmest\OneDrive\Desktop\generative AI\Unique3D-main\Unique3D-main\app\custom_models\mvimg_prediction.py", line 8, in <module>
    from app.custom_models.utils import load_pipeline
  File "C:\Users\mmest\OneDrive\Desktop\generative AI\Unique3D-main\Unique3D-main\app\custom_models\utils.py", line 6, in <module>
    from custum_3d_diffusion import modules
  File "C:\Users\mmest\OneDrive\Desktop\generative AI\Unique3D-main\Unique3D-main\custum_3d_diffusion\modules.py", line 14, in <module>
    from custum_3d_diffusion.trainings import base, image2mvimage_trainer, image2image_trainer
  File "C:\Users\mmest\OneDrive\Desktop\generative AI\Unique3D-main\Unique3D-main\custum_3d_diffusion\trainings\base.py", line 9, in <module>
    from diffusers.utils import make_image_grid
  File "C:\Users\mmest\.conda\envs\unique3d-py311\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\mmest\.conda\envs\unique3d-py311\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\mmest\.conda\envs\unique3d-py311\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\mmest\.conda\envs\unique3d-py311\Lib\site-packages\huggingface_hub\__init__.py)

**Comment by mmestiri** [comment]
this resolve it : pip install torch==2.2.0 torchvision torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121

**Comment by XKMEXX** [comment]
> this resolve it : pip install torch==2.2.0 torchvision torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121

It didn't help

**Comment by lianqu008** [comment]
from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\ProgramData\anaconda3\envs\unique3d-py311\Lib\site-packages\huggingface_hub\__init__.py)          The same problem, how to solve it,Also installed this:pip install torch==2.2.0 torchvision torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121

**Comment by x3272014653** [comment]
直接cmd运行不了
C：\Users\x3272>python app/gradio_local.py --port 7860
回溯（最近一次调用最后一次调用）：
文件“C：\Users\x3272\app\gradio_local.py”，第 17 行，在
导入 gradio 作为 gr
文件“C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\gradio_init_.py”，第 3 行，在
导入 gradio。simple_templates
文件“C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\gradio_simple_templates_init.py”，第 1 行，从
.simpledropdown 导入 SimpleDropdown
文件“C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\gradio_simple_templates\simpledropdown.py”，第 7 行，在 from gradio.components.base import Component， FormComponent
中
文件“C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\gradio\components_init_.py”，第 1 行，gradio.components.annotated_image
导入 AnnotatedImage
文件“C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\gradio\components\annotated_image.py”，第 8 行，导入
gradio_client.utils 作为client_utils
文件“C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\gradio_client_init_.py“，第 1 行，从
gradio_client.client 导入客户端
文件”C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\gradio_client\client.py“，第 29 行，导入
huggingface_hub
ModuleNotFoundError：没有名为”huggingface_hub“的模块。

在虚拟环境下也不能运行
（unique3d-py311） C：\Users\x3272>python app\gradio_local.py --port 7860
回溯（最近调用最后一次）：
文件 “C：\Users\x3272\app\gradio_local.py”，第 20 行，in
from app.gradio_3dgen import create_ui as create_3d_ui
文件 “C：\Users\x3272\app\gradio_3dgen.py”，第 6 行，in
from app.custom_models.mvimg_prediction import run_mvprediction
文件 “C：\Users\x3272\app\custom_models\mvimg_prediction.py“，第 8 行，
来自 app.custom_models.utils 导入load_pipeline
文件 ”C：\Users\x3272\app\custom_models\utils.py“，第 6 行，来自
custum_3d_diffusion 导入模块
文件 ”C：\Users\x3272\custum_3d_diffusion\modules.py“，第 14 行，来自
custum_3d_diffusion.trainings 导入基础、image2mvimage_trainer、image2image_trainer
文件“C：\Users\x3272\custum_3d_diffusion\trainings\base.py”，第 9 行，来自
diffusers.utils import make_image_grid
文件“C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\diffusers_init_.py”，第 5 行，来自
.utils import （
文件“C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\diffusers\utils_init_.py”，第 38 行，在
from .dynamic_modules_utils import get_class_from_dynamic_module
File “C：\Users\x3272\AppData\Roaming\Python\Python311\site-packages\diffusers\utils\dynamic_modules_utils.py”，第 28 行，huggingface_hub
导入cached_download、hf_hub_download model_info
ImportError：无法从“huggingface_hub”导入名称“cached_download”（C：\Users\x3272.conda\envs\unique3d-py311\Lib\site-packages\huggingface_hub_init_.py）

要怎么解决？

**Comment by ZFHung** [comment]
how to fix this ?

(unique3d-py311) D:\PicToMesh\Unique3D-main>python app/gradio_local.py --port 7860
C:\Users\Prestige\anaconda3\envs\unique3d-py311\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
C:\Users\Prestige\anaconda3\envs\unique3d-py311\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
Warning! extra parameter in cli is not verified, may cause erros.
D:\PicToMesh\Unique3D-main\app\custom_models\utils.py:62: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(load_from_checkpoint)
Expected types for unet: ['UNet2DConditionModel'], got UnifieldWrappedUNet.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 384.62it/s]
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2mvimg.StableDiffusionImage2MVCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Warning! extra parameter in cli is not verified, may cause erros.
An error occurred while trying to fetch lambdalabs/sd-image-variations-diffusers: lambdalabs/sd-image-variations-diffusers does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
An error occurred while trying to fetch lambdalabs/sd-image-variations-diffusers: lambdalabs/sd-image-variations-diffusers does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
An error occurred while trying to fetch lambdalabs/sd-image-variations-diffusers: lambdalabs/sd-image-variations-diffusers does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Expected types for unet: ['UNet2DConditionModel'], got UnifieldWrappedUNet.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 4997.98it/s]
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2img.StableDiffusionImageCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
C:\Users\Prestige\anaconda3\envs\unique3d-py311\Lib\site-packages\torch\utils\cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:05<00:00,  1.07it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Traceback (most recent call last):
  File "D:\PicToMesh\Unique3D-main\app\gradio_local.py", line 71, in <module>
    launch(
  File "D:\PicToMesh\Unique3D-main\app\gradio_local.py", line 40, in launch
    model_zoo.init_models()
  File "D:\PicToMesh\Unique3D-main\app\all_models.py", line 20, in init_models
    self._pipe_disney_controlnet_lineart_ipadapter_i2i = load_common_sd15_pipe(base_model=self.base_model, ip_adapter=True, plus_model=False, controlnet="./ckpt/controlnet-tile", pipeline_class=StableDiffusionControlNetImg2ImgPipeline)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PicToMesh\Unique3D-main\scripts\sd_model_zoo.py", line 92, in load_common_sd15_pipe
    pipe: StableDiffusionPipeline = model_from_ckpt_or_pretrained(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PicToMesh\Unique3D-main\scripts\sd_model_zoo.py", line 36, in model_from_ckpt_or_pretrained
    pipe = model_cls.from_pretrained(ckpt_or_pretrained, torch_dtype=torch_dtype, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prestige\AppData\Roaming\Python\Python311\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prestige\anaconda3\envs\unique3d-py311\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 710, in from_pretrained
    raise NotImplementedError(
NotImplementedError: auto not supported. Supported strategies are: balanced

**Comment by 333zzzsss** [comment]
Has anyone successfully reproduced this on Windows? Can you share the requirements.txt
?

**Comment by IIIIIIIllllllllIIIII** [comment]
Dont even try... its worthless....
