### ISSUE TITLE
I Don't know, why uninstall onnxruntime and onnxruntime-gpu

### ISSUE THREAD

**Issue by jazzydog** [AiuniAI/Unique3D#40]

**Comment by jtydhr88** [comment]
Do you mean in Windows bat script or windows install steps ?
If yes, this is because the default installation of onnxruntime and onnxruntime-gpu will install the version built for CUDA 11.x.
But just I mentioned in the ticket https://github.com/AiuniAI/Unique3D/issues/15, my env is **CUDA 12.1**, and according to onnxruntime official doc here - https://onnxruntime.ai/docs/install/
![image](https://github.com/AiuniAI/Unique3D/assets/860985/667a1df5-5bf2-485c-a994-df0c6bd950dc)
the correct index for onnxruntime and command should be:
pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
this is the reason why we need to unstall them first, then re-install by this link.

if your env is CUDA 11.8, I believe you don't need this step.
