### ISSUE TITLE
Release Date for New Code with Depth Supervision and Expanded Multi-Angle Model

### ISSUE THREAD

**Issue by aleksaknezevic24** [AiuniAI/Unique3D#75]
I wanted to inquire about the release of the new code that includes depth supervision and the updated model with more than 4 different angles of view. According to your previous communications, this release was expected in July (this month). However, as of now, there have been no updates or releases.

Could you please provide an update on when we can expect this new release?

Thank you for your attention to this matter. Looking forward to your response.

**Comment by wukailu** [comment]
We completed training on the depth supervised version, but found that adding the depth model did not result in an effective boost. This is because the inaccuracy of the depth model itself may instead cause the reconstruction results to crash. Although adding a depth model improves stability in the case of object classes such as buildings and vehicles, adding a depth model in the case of character instead reduces the quality of generation. Therefore we consider adding it as a separate branch afterwards.

**Comment by josepmy** [comment]
May I ask if exist any update about the 6 multiview update?
