### ISSUE TITLE
EP Error when using TensorrtExecutionProvider and CUDAExecutionProvider

### ISSUE THREAD

**Issue by trueices** [AiuniAI/Unique3D#77]
When I run the project on my ubuntu server, this error occurred and its generation time is quite slow over 10 mins.
 
![Untitled](https://github.com/user-attachments/assets/9e9ed576-df33-4419-bbba-d73b37924a47)

**Comment by wukailu** [comment]
This error is because your tensorrt backend for onnxruntime is not installed, so onnxruntime fails and switches to its default backend (which is very, very slow), a straightforward solution is to comment out TensorrtExecutionProvider in https://github.com/AiuniAI/Unique3D/blob/ 4263b8c836950babedd9c8b6769aa7c41afa9dbc/scripts/load_onnx.py#L5 , and keep only CUDAExecutionProvider.
